[tool.pytest.ini_options]
markers = [
    "mark4: tests for level 4",
    "mark6: tests for level 6",
    "mark8: tests for level 8",
    "mark10: tests for level 10",
    "lab_1_classify_by_unigrams: tests for lab 1",
    "lab_2_tokenize_by_bpe: tests for lab 2"
]
norecursedirs = [
    "venv*"
]

[tool.coverage.run]
omit = [
    '*/tests/*',
    '*/start.py'
]

[tool.mypy]
python_version = '3.10'
exclude = [
    'venv*',
    'test.py'
]

disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true

# simplifications
disable_error_code = [
    'var-annotated',
    'union-attr',
    # needed for seminars, to this moment not fixed: https://github.com/python/mypy/issues/9440
    'attr-defined'
]

[[tool.mypy.overrides]]
module = ['memory_profiler', 'ghapi.all', 'ast_comments', 'pydantic', 'transformers']
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ['seminars.*', ]
disable_error_code = [
    'empty-body'
]

[[tool.mypy.overrides]]
module = ['*.nmt_demo.*', ]
disable_error_code = [
    'no-any-unimported',
    'no-any-return'
]

[tool.black]
line-length = 100
target-version = ['py310']

[tool.isort]
py_version = '310'
skip_gitignore = true
line_length = 100
order_by_type = true
remove_redundant_aliases = true
group_by_package = true
force_alphabetical_sort_within_sections = true
